Moved: GCP Runner's Authentication above auto-approve .tfvars

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -26,6 +26,10 @@ jobs:
         run: terraform init
         working-directory: ${{ github.workspace }}/terraform-scripts
 
+      # Google authentication flow needs to run before running terraform-apply
+      - name: Run Google Cloud Authentication
+        run: gh workflow run ci-google-auth.yml || true # Ensures it doesn't fail the pipeline
+
       - name: Auto apply variables
         run: terraform apply -auto-approve -var-file=terraform.auto.tfvars
         working-directory: ${{ github.workspace }}/terraform-scripts
@@ -33,10 +37,6 @@ jobs:
       - name: Validate Terraform
         run: terraform validate
         working-directory: ${{ github.workspace }}/terraform-scripts
-
-      # Google authentication flow needs to run before running terraform-apply
-      - name: Run Google Cloud Authentication
-        run: gh workflow run ci-google-auth.yml || true # Ensures it doesn't fail the pipeline
 
       - name: Apply Terraform Changes
         run: terraform apply -auto-approve
